scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: pycodestyle 

pycodestyle:
    max-line-length: 120  # Default is 79 in PEP 8
