FROM tiagopeixoto/graph-tool
RUN pacman -S --noconfirm base-devel
RUN pacman -S --noconfirm wget
RUN pacman -S --noconfirm python-pip
RUN pip install thinc==7.4.0
RUN pip install kgtk


# Below are my attempts to install miller
# RUN pacman -S --noconfirm git
# RUN pacman -S --noconfirm ctags
# RUN pacman -S --noconfirm valgrind
# RUN pacman -S --noconfirm asciidoc
# RUN useradd --no-create-home --shell=/bin/false build && usermod -L build
# RUN echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# RUN git clone https://aur.archlinux.org/miller.git
# RUN chown -R build miller
# USER build
# RUN cd miller && makepkg -si

# USER root
# RUN pacman -U *.pkg.tar.xz