name: Run Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
# 11-Oct-2021: Adding the system conda gives pip
# access python 3.9 site packages:
#
# /usr/share/miniconda/lib/python3.9/site-packages 
#
# We'd prefer to use python 3.8 consistently while
# chasing down problems.
#
#      - name: Add conda to system path
#        run: |
#          echo $CONDA/bin >> $GITHUB_PATH
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: '3.8'
          conda-channels: anaconda, conda-forge
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install coveralls
          python -m spacy download en_core_web_sm
          conda install -c conda-forge graph-tool
# 11-Oct-2021: Do not use rdflib 6.0.0 and later, at
# the moment there's a fatal interaction, probably with ETK.
# See issues #537 and #538.
#
# pip uninstall -y rdflib
# pip install git+https://github.com/RDFLib/rdflib.git@master
      - name: Run Tests
        run: |
          cd tests
          coverage run --source=kgtk -m unittest discover      
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
